services:
  - type: web
    name: podcast-app
    env: python
    buildCommand: "python -m ensurepip --upgrade && pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: NEWSDATA_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false